name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v3
      # sets up .NET Core SDK 3.1
      - name: Setup .NET Core SDK
        uses: 
          actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      # Publish the site
      - name: Publish
        run: dotnet publish Portfolio.sln -c:Release -o:publish -p:GHPages=true
      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish/wwwroot
          force_orphan: true